// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed Icon.png
var resourceIconPng []byte
var bundled = &fyne.StaticResource{
	StaticName:    "./Icon.png",
	StaticContent: resourceIconPng,
}
