// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentTime():Promise<string>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function Greet(arg1:string):Promise<string>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function ShowOpenDialog():Promise<string>;
